HW 7. Terraform-2
Otus-DevOps-2023-09/DmitryArmyanovsky_infra pull request #6
Opened 2023-11-22 19:22 UTC by DmitryArmyanovsky

# Выполнено ДЗ №

 - [+] Основное ДЗ
 - [-] Задание со *

## В процессе сделано:
- Приложение разделено на 2 ВМ
- Описание конфигураций ВМ вынесено в модули
- Создано 2 окружения - stage и prod

## PR checklist
 - [+] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2023-11-23 09:56 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментрий к файлу
Так же попробуйте настроить удаленное хранение стейта
Пример можно посмотреть тут https://cloud.yandex.ru/docs/tutorials/infrastructure-management/terraform-state-storage

2023-11-23 09:56 UTC, mrgreyves commented on terraform/terraform
> +-----BEGIN OPENSSH PRIVATE KEY-----
Ключи в репе, да еще и приватные =)
Такое точно стоит удалить =)

2023-11-23 18:47 UTC, DmitryArmyanovsky commented on terraform/terraform
> +-----BEGIN OPENSSH PRIVATE KEY-----
Добрый вечер. 
Ключик удалил и настроил удаленное хранение стейта.

2023-11-24 13:23 UTC, mrgreyves approved these changes
Здравствуйте!)
Можете пропустить историю с удаленным хранение стейта
Но на досуге рекомендую ознакомиться

2023-11-24 13:44 UTC, merged